### ISSUE TITLE
Build sending welcoming Email function for mentees who finish filling out the form

### ISSUE THREAD

**Issue by wrc9817** [jpabadir/pace-c#256]

**Comment by jpabadir** [comment]
This will require a bit of creativity, because we're not creating an account for mentees, and thus you can't just say user.sendEmail(). So if I were you I would try to 1: 
1. See if Firebase allows us to send an email to an email address without that address being linked to a registered user;
2. If not, look up how to send an email from the FE JS, there may be an npm package we can use, or something like that. Below is a tutorial I found. 

https://www.google.com/search?q=send+email+front+end+javascript&pws=0&gl=us&gws_rd=cr
https://dev.to/iwaniukooo11/send-e-mails-directly-from-front-end-with-js-5d7d
