### ISSUE TITLE
Look into the backend security 

### ISSUE THREAD

**Issue by jpabadir** [jpabadir/pace-c#491]
Look into the back-end security of our website (https://github.com/public-apis/public-apis). Possibly also provide some ideas of how to configure Firebase so it's more secure (it's currently in test/developer mode. If this site it to be deployed, we should make a note of this for handover since in its current state, it'd be *really* insecure).

**Comment by katmartel** [comment]
For simplicity I'm directly copying and pasting this from my meeting notes, hopefully this helps: 

- When it comes to backend security, since we're using Firebase, the client recommends using [Firebase ID Tokens](https://firebase.google.com/docs/auth/admin/verify-id-tokens). She mentioned that we could send the ID Token based on the logged in user to the backend, then ensure that the token does in fact exist for that user before obtaining backend information. If the token does not exist, we could return an Authorization Error (401).
  - I asked the client about disabling CORS apart from our domain, and she said that would work as well. However, if we are able to secure the backend, she recommends using Firebase ID tokens.
